---
title: "topic-analysis-Nexis"
format: html
---

```{r}
#| output: false 
library(LexisNexisTools)
library(quanteda)
library(tm)
library(topicmodels)
library(topicdoc)   
library(tidyverse)
library(tidytext)
library(reshape2)
library(tictoc)
library(LDAvis)
library(tsne)
library(servr)
```

## Data 
```{r}
pre_files <- list.files(
  path = here::here("data", "Nexis2", "EU-SUP-bans"),   # update to your folder
  pattern = "\\.docx$",
  full.names = TRUE,
  recursive = TRUE,
  ignore.case = TRUE
)

pre_dat <- lnt_read(pre_files)

pre_meta_df       <- pre_dat@meta
pre_articles_df   <- pre_dat@articles
pre_paragraphs_df <- pre_dat@paragraphs

df <- tibble(
  date     = pre_meta_df$Date,
  headline = pre_meta_df$Headline,
  id       = pre_meta_df$ID,
  text     = pre_articles_df$Article,
  source   = pre_meta_df$Newspaper
)
```


## Build & Clean **Corpus**

Build the corpus
```{r}
#| warning: false 
#| output: false 
tbl <- df
corpus <- corpus(x = tbl, 
                 textg_field = "text")
```

Tokenize and clean 
```{r}
# Stop words 
add_stops <- c(quanteda::stopwords("en", 
                                   source="smart"),
               # remove other meta data words 
               "said", "says", "told", "according", "discuss", "because", "where", "vol", "pg", "newstex")


# Tokenize 
toks <- tokens(corpus, 
               remove_punct = TRUE, 
               remove_numbers = TRUE, 
               remove_symbols = TRUE) %>% 
  # Normalize
  tokens_tolower() 

# Remove stop words 
toks1 <- tokens_select(toks, pattern = add_stops, selection = "remove")
```

## Build the Document-Feature Matrix

```{r}
# Creating a dfms
dfm1 <- dfm(toks1) 
dfm2 <- dfm_trim(dfm1, 
                 min_docfreq = 5,  # Reduce by limiting min values of feature's doc frequency
                 min_termfreq = 10) # appears at least 10 times total

# Remove empty rows b/c LDA will error on these
sel_idx <- slam::row_sums(dfm2) > 0 # select no empty rows 
dfm <- dfm2[sel_idx,] # subset
```

## Select K uysing Multiple Critiera 

Initialize Model (Theory-Driven k)
```{r}
# Define Hyperparameter 
k <- 3

# Model 
topicModel_k3 <- LDA(dfm, # matrix
                      k, 
                      method = "Gibbs", # Gibbs is default (always do this)
                      control = list(iter = 100, # Number of iterations
                                     verbose = 25, # Tell us after every 25 iterations
                                     seed = 321
                                     ))

```

Evaluate 
```{r}
result <- posterior(topicModel_k3)

beta  <- result$terms
theta <- result$topcis

cat("phi dimensions  (topics × vocab):", dim(beta), "\n")

# Top 10 terms per topic
terms(topicModel_k3, 10)
```

## Selecting k with Coherence Scores
```{r}
# Fit model for a range of k values
k_values <- seq(2, 15, by = 1) 

tic() # Timerstart


# Increase iterations
coherence_results <- map_dfr(k_values, function(k){
  # Run the model 
  m <- LDA(dfm, k = k, 
      method = "Gibbs", 
      control = list(iter = 1000,   # was 300
                     burnin = 200,  # discard first 200 iterations
                     seed = 231,
                     verbose = 0))
   # Calculate coherence 
  coh <- mean(topic_coherence(m, dfm))
  tibble(k = k, coherence = coh)
})

toc() # Timer end 
```

Plotting coherence VS K
```{r}
ggplot(coherence_results, aes(x = k, y = coherence)) +
  geom_line(color = "darkorchid4") +
  geom_point(color = "darkorchid4", size = 2) +
  geom_vline(xintercept = coherence_results$k[which.max(coherence_results$coherence)], # Best coh score 
             linetype = "dashed", color = "violetred2") +
  labs(title = "Mean topic coherence by number of topics (k)",
       subtitle = "Dashed line = k with highest coherence",
       x = "Number of topics (k)",
       y = "Mean coherence score") +
  theme_minimal()
```


Bad idea.... The topic is already specific enough and splitting it into futher groups doesn't make sense. 
